### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE] with http-content-encoding on `gzip, deflate, br`

### ISSUE THREAD

**Issue by AntonOellerer** [middyjs/middy#1037]
**Describe the bug**
I am creating a sls endpoint service with middy.
During testing with `sls invoke`/`curl` everything worked nice, but when I sent requests using Postman, I received `500 internal server error`s.
Examining it, I pinned the problem down to the `Accept-Encoding: gzip, deflate, br` header sent by Postman.
In the logs, I am seeing the following:

```
2023-04-04 16:20:38.424 INFO
2023-04-04 16:20:38.424 ERROR   TypeError [ERR_INVALID_ARG_TYPE]: The "iterable" argument must be an instance of Iterable. Received an instance of Object
    at __node_internal_captureLargerStackTrace (node:internal/errors:491:5)
    at new NodeError (node:internal/errors:400:5)
    at from (node:internal/streams/from:36:11)
    at Readable.from (node:internal/streams/readable:1390:10)
    at httpContentEncodingMiddlewareAfter (/var/task/src/functions/legacy/handler.js:181176:48)
    at runMiddlewares (/var/task/src/functions/legacy/handler.js:180641:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runRequest (/var/task/src/functions/legacy/handler.js:180618:7)
    at async /var/task/src/functions/legacy/handler.js:34582:16 {
  code: 'ERR_INVALID_ARG_TYPE'
}
2023-04-04 16:20:41.003 DEBUG   error while getting callsite source context: ENOENT: no such file or directory, open '/node_modules/@middy/http-content-encoding/index.js'
2023-04-04 16:20:41.003 DEBUG   error while getting callsite source context: ENOENT: no such file or directory, open '/node_modules/@middy/core/index.js'
2023-04-04 16:20:41.003 DEBUG   error while getting callsite source context: ENOENT: no such file or directory, open '/node_modules/@middy/core/index.js'
2023-04-04 16:20:41.004 DEBUG   error while getting callsite source context: ENOENT: no such file or directory, open '/node_modules/src/awslambda.ts'
2023-04-04 16:20:41.019 ERROR   Invoke Error    {"errorType":"TypeError","errorMessage":"The \"iterable\" argument must be an instance of Iterable. Received an instance of Object","code":"ERR_INVALID_ARG_TYPE","stack":["TypeError [ERR_INVALID_ARG_TYPE]: The \"iterable\" argument must be an instance of Iterable. Received an instance of Object","    at __node_internal_captureLargerStackTrace (node:internal/errors:491:5)","    at new NodeError (node:internal/errors:400:5)","    at from (node:internal/streams/from:36:11)","    at Readable.from (node:internal/streams/readable:1390:10)","    at httpContentEncodingMiddlewareAfter (/var/task/src/functions/legacy/handler.js:181176:48)","    at runMiddlewares (/var/task/src/functions/legacy/handler.js:180641:23)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async runRequest (/var/task/src/functions/legacy/handler.js:180618:7)","    at async /var/task/src/functions/legacy/handler.js:34582:16"]}
```

Do you know how to fix this?

**To Reproduce**
How to reproduce the behaviour:
1. Create a serverless function with middy, using the `http-content-encoding` middleware
2. Deploy
3. Send a request using Postman
4. Thrown error
5. Examine logs

**Expected behaviour**
I receive the same response as if testing with `curl`

**Environment (please complete the following information):**
 - Node.js: v18.15.0
 - Middy: v4.2.8
 - AWS SDK: 3.303.0
 - serverless: 3.28.1
 - typescript: 5.0.3

**Comment by willfarrell** [comment]
`The "iterable" argument must be an instance of Iterable. Received an instance of Object` says your `body` is an object which cannot be encoded. It needs to be stringified first.

**Comment by AntonOellerer** [comment]
Ok, thank you!
