### ISSUE TITLE
Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'stream/promises'

### ISSUE THREAD

**Issue by MaazDev** [middyjs/middy#1049]
**Describe the bug**
when using middy with the aws cdk I recieve the following error:
```
{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'stream/promises'\nRequire stack:\n- /var/task/index.js\n- 
/var/runtime/UserFunction.js\n- /var/runtime/Runtime.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module 'stream/promises'","Require stack:","- /var/task/index.js","- /var/runtime/UserFunction.js","- /var/runtime/Runtime.j
s","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:225:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:300:17)","    at Object.<anonymous> (/var/runtime/index.js:43:34)","    at Module._compile (internal/modules
/cjs/loader.js:1114:14)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)","    at Module.load (internal/modules/cjs/loader.js:979:32)","    at Function.Module._load (internal/modules/cjs/loader.js:819:12)","    at Function.executeU
serEntryPoint [as runMain] (internal/modules/run_main.js:75:12)","    at internal/main/run_main_module.js:17:47"]}
```

**To Reproduce**
How to reproduce the behaviour:
1. cdk init --language=typescript
2. past this code in the stack
```
import * as cdk from 'aws-cdk-lib';
import {Construct} from 'constructs';
import {NodejsFunction} from "aws-cdk-lib/aws-lambda-nodejs";
import {FunctionUrlAuthType} from "aws-cdk-lib/aws-lambda";
export class MiddyTestStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const fn = new NodejsFunction(this, 'MiddyTestFunction', {
      retryAttempts: 0,
        entry: __dirname + '/runtime/index.ts',
      handler: 'handler',
      functionName: 'MiddyTestFunction',
    })
    const url = fn.addFunctionUrl({authType: FunctionUrlAuthType.NONE})

    console.log("function URL: " + url.url)
  }
}
```
3. create a runtime/index.ts file and past this code
```
import middy from "@middy/core";

export const handler = middy(async (event, context) => {
    console.log("working")
    return {
        statusCode: 200,
        body: JSON.stringify({
            message: "Hello world"
        }),
    }
})
```
Obviously middy was installed this is my package.json
```
{
  "name": "middy_test",
  "version": "0.1.0",
  "bin": {
    "middy_test": "bin/middy_test.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "cdk": "cdk"
  },
  "devDependencies": {
    "@types/aws-lambda": "^8.10.114",
    "@types/jest": "^29.4.0",
    "@types/node": "18.14.6",
    "aws-cdk": "2.75.0",
    "jest": "^29.5.0",
    "ts-jest": "^29.0.5",
    "ts-node": "^10.9.1",
    "typescript": "~4.9.5"
  },
  "dependencies": {
    "@middy/core": "^4.4.0",
    "aws-cdk-lib": "2.75.0",
    "constructs": "^10.0.0",
    "source-map-support": "^0.5.21"
  }
}
```
4. run cdk bootstrap && cdk watch --hotswap-fallback to deploy
5. go in ur lambda console and run the function with the function URL , check the logs and you will see the error
6. I have tried removing middy and it works perfectly

**Expected behaviour**
No error runtime import error should happen

**Environment (please complete the following information):**
 - Node.js: v18.15.0
 - Middy: 4.4.0

**Additional context**

**Comment by MaazDev** [comment]
runtime: Runtime.NODEJS_18_X needed

**Comment by willfarrell** [comment]
`node:stream/promises` was recently added (v4.3.0) to support the new streamifyResponse feature.
