### ISSUE TITLE
import @middy/core results in TypeError: core_1.default is not a function

### ISSUE THREAD

**Issue by samwaterlily** [middyjs/middy#1080]
**Describe the bug**
I'm using `@middy/core` and when I use the default import it return `undefined` and I get a `TypeError` trying co call `middy(...)`.

**To Reproduce**

* Sample code `handler => middy(handler).use(middyJsonBodyParser())`
* Full example and configs below
* Thrown error
    ```
    Cannot load "serverless.ts": Initialization error: TypeError: core_1.default is not a function
        at middyfy (/Users/samuelneff/projects/waterlily/waterlily-ltc-planning-app/packages/server/src/libs/lambda.ts:7:38)
        at Object.<anonymous> (/Users/samuelneff/projects/waterlily/waterlily-ltc-planning-app/packages/server/src/functions/api/handler.ts:18:28)
    ```

**Expected behaviour**
Import should return function that can be called.

**Environment (please complete the following information):**
 - Environment: darwin
 - node 18.17.0
 - framework 3.33.0 (local)
 - plugin 6.2.3
 - SDK 4.3.2
 - TypeScript: 4.9.5
 
**Additional context**

Debugging tried:
- `console.log({ middy })` outputs `{ middy: undefined }`
- Added to `tsconfig.json`: `"allowSyntheticDefaultImports": true,` (tried with and without)
- Deleted `.esbuild` folder

**Relevant code snippets**

Most of the code is barely changed from default generated code.

```ts
// handler.ts
import type { ValidatedEventAPIGatewayProxyEvent } from '@libs/api-gateway';
import { formatJSONResponse } from '@libs/api-gateway';
import { handlerPath } from '@libs/handler-resolver';
import { middyfy } from '@libs/lambda';

const api: ValidatedEventAPIGatewayProxyEvent<typeof schema> = async event => {
  return formatJSONResponse({
    message: `REST Lambda goes here.`,
    event,
  });
};

export const main = middyfy(api);

export default {
  handler: `${handlerPath(__dirname)}/handler.main`,
  events: [
    {
      http: {
        method: "*",
        path: "/{proxy+}"
      },
    },
  ],
};

// lambda.ts
import middy from "@middy/core";
import middyJsonBodyParser from "@middy/http-json-body-parser";

export const middyfy = (handler) => {
  // Error on next line
  const middyHandler = middy(handler);
  const result = middyHandler.use(middyJsonBodyParser());
  return result;
};

// package.json snippet
  "dependencies": {
    "@middy/core": "^3.4.0",
    "@middy/http-json-body-parser": "^3.4.0"
  },
```

Thanks!

**Comment by willfarrell** [comment]
Is this an issue using that latest version of Middy?

Please note we're planning to stop supporting cjs in the next major release. Because of this, breaking changes involving cjs won't be fixed.

**Comment by willfarrell** [comment]
> Is this an issue using that latest version of Middy?

Closing due to lack of reply.
