### ISSUE TITLE
Please give more descriptive error when throwing "Failed to resolve internal values" in secrets-manager module

### ISSUE THREAD

**Issue by jcollum-nutrien** [middyjs/middy#1184]
**Is your feature request related to a problem? Please describe.**

Related to https://github.com/middyjs/middy/issues/1177 

But I've run into this a lot. Usually it's related to a middleware failing to fetch a value from AWS SSM. Still, in a deployed lambda the error gives us nothing to go on, it's vague and unhelpful. 

```
{"errorType":"Error","errorMessage":"Failed to resolve internal values","stack":["Error: Failed to resolve internal values"," at getInternal (/var/task/node_modules/@middy/util/index.cjs:121:15)"," at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"," at async Object.secretsManagerMiddlewareBefore [as before] (/var/task/node_modules/@middy/secrets-manager/index.cjs:70:26)"," at before (/var/task/node_modules/@foo/rds-utils/src/barMiddleware.ts:43:7)
```

Clearly the `barMiddleware` is failing but any more information than that would be really helpful. I've debugged this issue locally before and breakpointed on that line and there is helpful information in the local context. 

**Describe the solution you'd like**

Well it sucks but I don't have a clear "show me this information" here. Just something that helps me figure out what went wrong in a deployed lambda would be an improvement.

**Comment by willfarrell** [comment]
A PR for this is welcome
