### ISSUE TITLE
EISDIR: illegal operation on a directory when doing a build

### ISSUE THREAD

**Issue by philipodev** [middyjs/middy#39]
Got this error when trying to do a build. Tried simple googling but couldnt find a suitable solution.

By first guess is that you try to copy a file to `fonts` which is a folder and cant be overriden.
I think we need to copy like this instead:
`node_modules/jsdoc/templates/default/static/fonts/OpenSans-Bold-webfont.eot' -> 'docs/middy/0.2.11/fonts/OpenSans-Bold-webfont.eot'`

Node Version: `8.5.0`
NPM Version: `5.3.0`

OS: `macOS Sierra`

Terminal Output:
```
$ npm run build

> middy@0.2.11 build /Users/philipandersson/Desktop/middy
> npm run build:docs && npm run build:readme


> middy@0.2.11 build:docs /Users/philipandersson/Desktop/middy
> jsdoc --readme README.md --package package.json --destination docs src

fs.js:1919
  binding.copyFile(src, dest, flags);
          ^

Error: EISDIR: illegal operation on a directory, copyfile '/Users/philipandersson/Desktop/middy/node_modules/jsdoc/templates/default/static/fonts/OpenSans-Bold-webfont.eot' -> 'docs/middy/0.2.11/fonts'
    at Object.fs.copyFileSync (fs.js:1919:11)
    at /Users/philipandersson/Desktop/middy/node_modules/jsdoc/templates/default/publish.js:516:12
    at Array.forEach (<anonymous>)
    at Object.exports.publish (/Users/philipandersson/Desktop/middy/node_modules/jsdoc/templates/default/publish.js:512:17)
    at Object.module.exports.cli.generateDocs (/Users/philipandersson/Desktop/middy/node_modules/jsdoc/cli.js:448:35)
    at Object.module.exports.cli.processParseResults (/Users/philipandersson/Desktop/middy/node_modules/jsdoc/cli.js:399:20)
    at module.exports.cli.main (/Users/philipandersson/Desktop/middy/node_modules/jsdoc/cli.js:240:14)
    at Object.module.exports.cli.runCommand (/Users/philipandersson/Desktop/middy/node_modules/jsdoc/cli.js:189:5)
    at /Users/philipandersson/Desktop/middy/node_modules/jsdoc/jsdoc.js:105:9
    at Object.<anonymous> (/Users/philipandersson/Desktop/middy/node_modules/jsdoc/jsdoc.js:106:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! middy@0.2.11 build:docs: `jsdoc --readme README.md --package package.json --destination docs src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the middy@0.2.11 build:docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/philipandersson/.npm/_logs/2017-10-02T22_22_28_445Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! middy@0.2.11 build: `npm run build:docs && npm run build:readme`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the middy@0.2.11 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/philipandersson/.npm/_logs/2017-10-02T22_22_28_462Z-debug.log
```

**Comment by lmammino** [comment]
Hello @philipodev,

Unfortunately, I wasn't able to reproduce your issue, I guess it might be system specific.

One thing I did was to update the `jsdoc` version used by middy to build the docs file.

Can you try to use the current master, delete your `docs` folder (if you have it) and then try to run `npm run build` again?

I hope this will address your issue.

**Comment by philipodev** [comment]
Great, thanks. It worked with the new master. :)

**Comment by lmammino** [comment]
Awesome, thanks for testing it so quickly :)
