### ISSUE TITLE
FunctionShield fails to run on nodejs v12

### ISSUE THREAD

**Issue by willfarrell** [middyjs/middy#460]
CloudWatch Error
```
undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Error",
    "errorMessage": "No native build was found for runtime=node abi=72 platform=linuxglibc arch=x64",
    "stack": [
        "Error: No native build was found for runtime=node abi=72 platform=linuxglibc arch=x64",
        "    at Function.load.path (/var/task/node_modules/node-gyp-build/index.js:59:9)",
        "    at load (/var/task/node_modules/node-gyp-build/index.js:19:30)",
        "    at Object.<anonymous> (/var/task/node_modules/@puresec/function-shield/dist/index.js:1:1078)",
        "    at c (/var/task/node_modules/@puresec/function-shield/dist/index.js:1:158)",
        "    at /var/task/node_modules/@puresec/function-shield/dist/index.js:1:962",
        "    at Object.<anonymous> (/var/task/node_modules/@puresec/function-shield/dist/index.js:1:971)",
        "    at Module._compile (internal/modules/cjs/loader.js:956:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)",
        "    at Module.load (internal/modules/cjs/loader.js:812:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:724:14)",
        "    at Module.require (internal/modules/cjs/loader.js:849:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at Object.<anonymous> (/var/task/node_modules/@middy/function-shield/index.js:1:24)",
        "    at Module._compile (internal/modules/cjs/loader.js:956:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)",
        "    at Module.load (internal/modules/cjs/loader.js:812:32)"
    ]
}
```

Also noticed that redirect https://www.puresec.io/product to https://www.paloaltonetworks.com/prisma/containers-serverless now. `puresec` got bought out?

Their [npm](https://www.npmjs.com/package/@puresec/function-shield) package hasn't been updated in over 3m and has declining use.

**Comment by willfarrell** [comment]
Did some digging, we need to update the version of our dep. I'll push a PR in a bit.

**Comment by willfarrell** [comment]
Bumped the dep version up to v2, still failing.

```
2020-01-05T23:44:04.596Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Error",
    "errorMessage": "No native build was found for platform=linux arch=x64 runtime=node abi=72 uv=1 libc=glibc",
    "stack": [
        "Error: No native build was found for platform=linux arch=x64 runtime=node abi=72 uv=1 libc=glibc",
        "    at Function.load.path (/var/task/node_modules/node-gyp-build/index.js:55:9)",
        "    at load (/var/task/node_modules/node-gyp-build/index.js:20:30)",
        "    at Object.<anonymous> (/var/task/node_modules/@puresec/function-shield/dist/index.js:1:1091)",
        "    at b (/var/task/node_modules/@puresec/function-shield/dist/index.js:1:158)",
        "    at /var/task/node_modules/@puresec/function-shield/dist/index.js:1:962",
        "    at Object.<anonymous> (/var/task/node_modules/@puresec/function-shield/dist/index.js:1:971)",
        "    at Module._compile (internal/modules/cjs/loader.js:956:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)",
        "    at Module.load (internal/modules/cjs/loader.js:812:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:724:14)",
        "    at Module.require (internal/modules/cjs/loader.js:849:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at Object.<anonymous> (/var/task/src/middleware/functionshield.js:1:24)",
        "    at Module._compile (internal/modules/cjs/loader.js:956:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)",
        "    at Module.load (internal/modules/cjs/loader.js:812:32)"
    ]
}
```

@0xh0b0 Any ideas?

We might have to deprecate the middleware. cc @lmammino

**Comment by 0xh0b0** [comment]
FunctionShield is no longer actively maintained and, probably, we'll never add support for Node.js v12.

**Comment by willfarrell** [comment]
@0xh0b0 Thanks for the update.

@lmammino I'll submit a PR shortly with a warning added (and version updated). I suggest we keep for v1, deprecate for v2 or end of 2020 when node v10 is deprecated.
