### ISSUE TITLE
[Question] Is there a way to silence the middy/validator console.error when running with jest.

### ISSUE THREAD

**Issue by Bored0ne** [middyjs/middy#565]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Write a jest test that fails validation
2. Get annoyed by console.error usage.

What happens?
-------------
Basically when my ci cd checks for "red" text it will pick up an expected validator error.

What were you expecting to happen?
----------------------------------
It to not output or to have a environment variable I can set to silent the error.

Any logs, error output, etc?
----------------------------
 console.error
    BadRequestError: Event object failed validation
        at before (/Users/stephen.seaton/WebstormProjects/apd-backend/node_modules/@middy/validator/index.js:62:23)
        at runNext (/Users/stephen.seaton/WebstormProjects/apd-backend/node_modules/@middy/core/index.js:78:24)
        at before (/Users/stephen.seaton/WebstormProjects/apd-backend/node_modules/@middy/http-json-body-parser/index.js:24:5)
        at runNext (/Users/stephen.seaton/WebstormProjects/apd-backend/node_modules/@middy/core/index.js:78:24)
        at runMiddlewares (/Users/stephen.seaton/WebstormProjects/apd-backend/node_modules/@middy/core/index.js:99:3)
        at /Users/stephen.seaton/WebstormProjects/apd-backend/node_modules/@middy/core/index.js:173:7
        at new Promise (<anonymous>)

Any other comments?
-------------------
I'd say an environment variable might be easiest to implement. But if this isn't something you want worked on I understand. Thanks in advance

What versions of software are you using?
----------------------------------------
**Node.js Version:** 14.8.0

**Middy Version:** 1.4.0

**AWS SDK Version:** 2.0.48

**Comment by willfarrell** [comment]
You could add `console.error = () => {}` to the top of the test file, that should do it. this could be add with an ENV. I'm open to a PR for it.
