### ISSUE TITLE
[@middy/warmup] handler.callback is not a function

### ISSUE THREAD

**Issue by vicary** [middyjs/middy#682]
What are the steps to reproduce this issue?
-------------------------------------------
1. `npm install @middy/warmup`
2. Create a Lambda named *test* with this line of code `module.exports.handler = middy(()=>"test").use(warmup());`
3. `npx sls invoke local -f test --data '{"source":"serverless-plugin-warmup"}'`

What happens?
-------------
```bash
Exiting early via warmup Middleware
handler.callback is not a function TypeError: handler.callback is not a function
    at before (/.../node_modules/@middy/warmup/index.js:18:24)
    at runMiddlewares (/.../node_modules/@middy/core/index.js:119:88)
    at runRequest (/.../node_modules/@middy/core/index.js:80:11)
    at instance (/.../node_modules/@middy/core/index.js:22:12)
    at /.../.webpack/hello/serverless_sdk/index.js:24:10545
    at /.../node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:877:30
    at new Promise (<anonymous>)
    at AwsInvokeLocal.invokeLocalNodeJs (/.../node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:830:12)
    at AwsInvokeLocal.invokeLocal (/.../node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:230:19)
    at Object.invoke:local:invoke [as hook] (/.../node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:49:47)
    at PluginManager.invoke (/.../node_modules/serverless/lib/classes/PluginManager.js:576:20)
    at async PluginManager.run (/.../node_modules/serverless/lib/classes/PluginManager.js:634:7)
    at async Serverless.run (/.../node_modules/serverless/lib/Serverless.js:327:5)
    at async /.../node_modules/serverless/scripts/serverless.js:704:9
```

What were you expecting to happen?
----------------------------------
```bash
Exiting early via warmup Middleware
```

Any logs, error output, etc?
----------------------------
See above

Any other comments?
-------------------
Looking at the JavaScript source of the plugin in `node_modules/@middy/warmup/index.js`, `handler.callback(...)` at line 18 doesn't seem right.

```js
module.exports = (config) => {
  const defaults = {
    isWarmingUp: (event) => event.source === 'serverless-plugin-warmup',
    onWarmup: (event) => console.log('Exiting early via warmup Middleware'),
    waitForEmptyEventLoop: null
  }

  const options = Object.assign({}, defaults, config)

  return ({
    before: (handler, next) => {
      console.log(handler);
      if (options.isWarmingUp(handler.event)) {
        options.onWarmup(handler.event)
        if (options.waitForEmptyEventLoop !== null) {
          handler.context.callbackWaitsForEmptyEventLoop = Boolean(options.waitForEmptyEventLoop)
        }
        return handler.callback(null, 'warmup')
      }

      next()
    }
  })
}
```

What versions of software are you using?
----------------------------------------
**Node.js Version:** v16.1.0

**Middy Version:** `@middy/core@2.2.0` `@middy/warmup@1.5.2`

**AWS SDK Version:** N/A

**Comment by vicary** [comment]
Is `@middy/warmup` meant to be deprecated? I think it is still using the v1.x syntax.

**Comment by willfarrell** [comment]
You are correct, `@middy/warmup` was deprecated when we moved to v2.x. You can read why and see a code sample to add it back in yourself in the upgrade documentation. https://github.com/middyjs/middy/blob/main/docs/UPGRADE.md#warmup

**Comment by vicary** [comment]
TBH Provisioned Concurrency is not a brainless drop-in replacement, because the startup time and insane cost when compared to warm ups.
