### ISSUE TITLE
Middy with Apollo Server

### ISSUE THREAD

**Issue by acaxon** [middyjs/middy#772]
What are the steps to reproduce this issue?
-------------------------------------------
1. Create a simple lambda function with Apollo Server and middy:

```js
import { ApolloServer, gql } from 'apollo-server-lambda'
import { buildFederatedSchema } from '@apollo/federation'
import middy from '@middy/core'
import { resolvers } from '../graphql/resolvers'
import { graphqlFileToStr } from '../graphql/schema'

const typeDefs = gql(graphqlFileToStr)

const server = new ApolloServer({
  schema: buildFederatedSchema({
    typeDefs,
    resolvers,
  })
})

const graphqlHandler = server.createHandler()
const handler = middy(graphqlHandler)

export { handler as apolloServer }

```

2. Now put a middy plugin - **httpJsonBodyParser**, for example:

```js
import { ApolloServer, gql } from 'apollo-server-lambda'
import { buildFederatedSchema } from '@apollo/federation'
import middy from '@middy/core'
import httpJsonBodyParser from '@middy/http-json-body-parser'
import { resolvers } from '../graphql/resolvers'
import { graphqlFileToStr } from '../graphql/schema'

const typeDefs = gql(graphqlFileToStr)

const server = new ApolloServer({
  schema: buildFederatedSchema({
    typeDefs,
    resolvers,
  })
})

const graphqlHandler = server.createHandler()
const handler = middy(graphqlHandler)
  .use([
    httpJsonBodyParser(),
  ])

export { handler as apolloServer }

```

What happens?
-------------

The first code works great, but the second return this:

```json
{
  "message": "Internal server error"
}
```

What were you expecting to happen?
----------------------------------
The second code to work as well.

Any logs, error output, etc?
----------------------------

The first code works great, but the second one break with the following log in CloudWatch:

```json
// ...

// 2022-01-05T17:08:37.532Z	64bd1144-3a4a-421b-96d4-a7556714a28f	ERROR	Unhandled Promise Rejection 	
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object",
    "reason": {
        "errorType": "TypeError",
        "errorMessage": "The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object",
        "code": "ERR_INVALID_ARG_TYPE",
        "stack": [
            "TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object",
            "    at Function.from (buffer.js:330:9)",
            "    at g (/var/task/src/frameworks/aws/webpack:/src/frameworks/aws/index.js:14485:17)",
            "    at m (/var/task/src/frameworks/aws/webpack:/src/frameworks/aws/index.js:14504:12)",
            "    at Object.g [as getRequest] (/var/task/src/frameworks/aws/webpack:/src/frameworks/aws/index.js:14154:60)",
            "    at r (/var/task/src/frameworks/aws/webpack:/src/frameworks/aws/index.js:15211:37)",
            "    at /var/task/src/frameworks/aws/webpack:/src/frameworks/aws/index.js:13991:9",
            "    at new Promise (<anonymous>)",
            "    at A (/var/task/src/frameworks/aws/webpack:/src/frameworks/aws/index.js:13978:12)",
            "    at N (/var/task/src/frameworks/aws/webpack:/src/frameworks/aws/index.js:14017:12)",
            "    at /var/task/src/frameworks/aws/webpack:/src/frameworks/aws/index.js:31606:27"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:314:20)",
        "    at process.emit (/var/task/src/frameworks/aws/webpack:/src/frameworks/aws/index.js:96568:21)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}
// ...
```

Any other comments?
-------------------
I don't know if it is the right place to post my issue. Sorry if not.

What versions of software are you using?
----------------------------------------
**Node JS**: 14.15.0

**Middy**: 2.5.3

**AWS SDK**: @^2.1033.0, aws-sdk@^2.1036.0, aws-sdk@^2.7.0 (yarn.lock)

**Comment by willfarrell** [comment]
I'm not familiar with Apollo, but maybe this will help: https://github.com/middyjs/middy/issues/527

**Comment by acaxon** [comment]
Thank you for the quick answer, [@willfarrell](https://github.com/willfarrell). I've seen this thread and tried it, but it didn't work, and I got this answer in CloudWatch:

```
2022-01-05T19:28:03.109Z	undefined	INFO	Enabling inline tracing for this federated service. To disable, use ApolloServerPluginInlineTraceDisabled.

2022-01-05T19:28:03.306Z	556b05b8-741c-47fa-b88f-c882226b93ff	INFO	Enabling inline tracing for this federated service. To disable, use ApolloServerPluginInlineTraceDisabled.

```

**Comment by acaxon** [comment]
I solved the problem, @willfarrell.

Apollo Server contributor [@glasser](https://github.com/glasser) helped me and told me Apollo Server already parses the body, and when _http-json-body-parser_ tried to do its job, the arguments it receives wasn't a string (because Apollo Server had "transformed" it in an object.

When I use other Middy plugins, it works great.

**Thank you** again for your **attention** and your **time**, @willfarrell. Closing this issue.
