### ISSUE TITLE
Serverless. Local invokation.

### ISSUE THREAD

**Issue by MadaShindeInai** [middyjs/middy#943]
**Describe the bug**
Getting an error when i try to run newly created lambda locally.

**To Reproduce**
How to reproduce the behaviour:
1. Install 'serverless' https://www.serverless.com/framework/docs/getting-started
2. Create lambda from template "`serverless create --template aws-nodejs-typescript --path myService`"
3. Go to created service `cd ./myService`
4. Install deps `yarn`. Middy and other packages will be installed.
5. Try to invoke locally `sls invoke local -f hello`  

**Error**  
```
**Running "serverless" from node_modules**
{
    "errorMessage": "Cannot read properties of undefined (reading 'Content-Type')",
    "errorType": "TypeError",
    "stackTrace": [
        "TypeError: Cannot read properties of undefined (reading 'Content-Type')",
        "    at httpJsonBodyParserMiddlewareBefore (/Users/sergeinepryahin/Documents/Nodejs/aws-in-nodejs-be/products-service/node_modules/@middy/http-json-body-parser/index.js:13:29)",
        "    at runMiddlewares (/Users/sergeinepryahin/Documents/Nodejs/aws-in-nodejs-be/products-service/node_modules/@middy/core/index.js:118:27)",
        "    at runRequest (/Users/sergeinepryahin/Documents/Nodejs/aws-in-nodejs-be/products-service/node_modules/@middy/core/index.js:78:15)",
        "    at middy2 (/Users/sergeinepryahin/Documents/Nodejs/aws-in-nodejs-be/products-service/node_modules/@middy/core/index.js:32:16)",
        "    at /Users/sergeinepryahin/Documents/Nodejs/aws-in-nodejs-be/products-service/node_modules/serverless/lib/plugins/aws/invoke-local/index.js:953:30",
        "    at new Promise (<anonymous>)",
        "    at AwsInvokeLocal.invokeLocalNodeJs (/Users/sergeinepryahin/Documents/Nodejs/aws-in-nodejs-be/products-service/node_modules/serverless/lib/plugins/aws/invoke-local/index.js:906:12)",
        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
    ]
}
```

**Expected behaviour**
I expect to get success response.

**Environment (please complete the following information):**
 - Node.js: [e.g. 16]
 - Middy: [e.g. 3.0.0]
 - AWS SDK [e.g. 2.1000.0]

**Additional context**

**Comment by MadaShindeInai** [comment]
Ah, inattentive me. Need to run locally specifying the path to the json file with mocks: `sls invoke local -f hello --path mock.json`
Unclear moment.
