### ISSUE TITLE
bug: middy validator v4 throws runtime exceptions due to esm-only ajv-cmd

### ISSUE THREAD

**Issue by JoshBarr** [middyjs/middy#947]
**Describe the bug**

Middy v4 depends on `ajv-cmd` package that appears to be [ESM-only](https://github.com/willfarrell/ajv-cmd/blob/main/package.json).

**To Reproduce**
How to reproduce the behaviour:

1. Install deps:
```sh
npm i @middy/core @middy/validator
```

2. Setup a handler:
```ts
import middy from "@middy/core";
import validatorMiddleware from "@middy/validator";
// This is missing types, but there's already an issue for it
import { transpileSchema } from "@middy/validator/transpile";

const schema = {
  type: 'object',
  required: ['body'],
  properties: {
    // this will pass validation
    body: {
      type: 'string'
    },
  }
}

const mw = middy((event, ctx) => { 
  return {}
}).use(validatorMiddleware({
  eventSchema: transpileSchema(schema)
}))
```
3. Bundle your lambda using CDK/esbuild.
```ts
import * as nodejs from "aws-cdk-lib/aws-lambda-nodejs";

const fn = new nodejs.NodejsFunction(this, id, {
  runtime: Runtime.NODEJS_16_X,
  architecture: Architecture.ARM_64,
  bundling: {
    sourceMap: true,
    sourcesContent: false,
  },
  // rest of config omitted
  ...rest,
})
```

Will result in runtime errors like:

```
{
    "errorType": "TypeError",
    "errorMessage": "The \"path\" argument must be of type string or an instance of URL. Received undefined",
    "code": "ERR_INVALID_ARG_TYPE",
    "stack": [
        "TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string or an instance of URL. Received undefined",
        "    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)",
        "    at new NodeError (node:internal/errors:372:5)",
        "    at fileURLToPath (node:internal/url:1420:11)",
        "    at Object.<anonymous> (/node_modules/ajv-cmd/transpile.js:11:27)",
        "    at Module._compile (node:internal/modules/cjs/loader:1105:14)",
        "    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)",
        "    at Module.load (node:internal/modules/cjs/loader:981:32)",
        "    at Function.Module._load (node:internal/modules/cjs/loader:822:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1005:19)",
        "    at require (node:internal/modules/cjs/helpers:102:18)",
        "    at _tryRequireFile (file:///var/runtime/index.mjs:915:37)",
        "    at _tryRequire (file:///var/runtime/index.mjs:965:25)",
        "    at _loadUserApp (file:///var/runtime/index.mjs:994:22)",
        "    at Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1035:27)",
        "    at start (file:///var/runtime/index.mjs:1200:42)",
        "    at file:///var/runtime/index.mjs:1206:7",
        "    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)",
        "    at async Promise.all (index 0)",
        "    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)",
        "    at async loadESM (node:internal/process/esm_loader:88:5)",
        "    at async handleMainPromise (node:internal/modules/run_main:61:12)"
    ]
}
```

**Expected behaviour**
The handler should not throw exceptions when running.

**Environment (please complete the following information):**
 - Node.js: 16.x
 - Middy: 4.0.0
 - AWS SDK 3.218.0

**Workaround**

```js
import * as nodejs from "aws-cdk-lib/aws-lambda-nodejs";
import { OutputFormat } from "aws-cdk-lib/aws-lambda-nodejs";

const fn = new nodejs.NodejsFunction(this, id, {
  runtime: Runtime.NODEJS_16_X,
  architecture: Architecture.ARM_64,
  bundling: {
    sourceMap: true,
    sourcesContent: false,
    // set format to ESM
    format: OutputFormat.ESM,
    // set target to esnext
    target: "esnext",
    // change output format to .mjs
    esbuildArgs: {
      "--out-extension:.js=.mjs": "",
    },
    // add require() interop 
    banner: `import { createRequire } from 'module';const require = createRequire(import.meta.url);`,
  },
  // rest of config omitted
  ...rest,
})
```

**Comment by willfarrell** [comment]
Thanks for reporting. 

`ajv-cmd` uses `const __dirname = dirname(fileURLToPath(import.meta.url))`, maybe I'll switch it up to use the tmpdir function instead. There was a reason I didn't, I don't remember why. This change should resolve the issue assume the built in bundler bundles and tree-shakes before transpiling.

**Comment by willfarrell** [comment]
I remembered why the path had to be in the same dir, to ensure ref to the node_modules was maintained when using as a cli. I'll push another update to ensure it's fixed for both use cases.
