### ISSUE TITLE
V4: require() of ES Module transpile.cjs not supported.

### ISSUE THREAD

**Issue by miladezzat** [middyjs/middy#953]
**Describe the bug**

**To Reproduce**
How to reproduce the behaviour:
1. Sample code
```
const validatorMiddleware = require('@middy/validator');
const { transpileSchema } = require('@middy/validator/transpile');

module.exports = (schema) =>
  validatorMiddleware({ eventSchema: transpileSchema(schema) });
```
2. Error
```
{
  "errorMessage": "require() of ES Module packages/node_modules/ajv-cmd/compile.js from packages/node_modules/@middy/validator/transpile.cjs not supported.\nInstead change the require of compile.js in packages/node_modules/@middy/validator/transpile.cjs to a dynamic import() which is available in all CommonJS modules.",
  "errorType": "Error",
  "stackTrace": [
    "Error [ERR_REQUIRE_ESM]: require() of ES Module packages/node_modules/ajv-cmd/compile.js from packages/node_modules/@middy/validator/transpile.cjs not supported.",
    "Instead change the require of compile.js in packages/node_modules/@middy/validator/transpile.cjs to a dynamic import() which is available in all CommonJS modules.",
    "at Object.<anonymous> (packages/node_modules/@middy/validator/transpile.cjs:15:43)",
    "at Object.<anonymous> (packages/lib/validations/validator.js:2:29)",
    "at Object.<anonymous> (packages/lib/validations/pagination.js:1:19)",
    "at Object.<anonymous> (packages/lib/handlers/organizations.js:3:33)",
    "at _tryRequireFile (packages/node_modules/serverless-offline/src/lambda/handler-runner/in-process-runner/aws-lambda-ric/UserFunction.js:209:35)",
    "at _tryRequire (packages/node_modules/serverless-offline/src/lambda/handler-runner/in-process-runner/aws-lambda-ric/UserFunction.js:269:23)",
    "at _loadUserApp (packages/node_modules/serverless-offline/src/lambda/handler-runner/in-process-runner/aws-lambda-ric/UserFunction.js:304:20)",
    "at module.exports.load (packages/node_modules/serverless-offline/src/lambda/handler-runner/in-process-runner/aws-lambda-ric/UserFunction.js:341:27)",
    "at InProcessRunner.run (file://packages/node_modules/serverless-offline/src/lambda/handler-runner/in-process-runner/InProcessRunner.js:41:27)"
  ]
}
```

**Expected behaviour**

**Environment (please complete the following information):**
 - Node.js: 18
 - Middy:  4.x
 - AWS SDK : serverless 3.x

**Additional context**

**Comment by willfarrell** [comment]
Thanks for reporting. Publishing ajv-cmd with both cjs/mjs should resolve it. I'll try and get to it over the weekend.

**Comment by willfarrell** [comment]
A possible fix will be released in v4.0.5 shortly. Please re-open this if it doesn't resolve your issue.

**Comment by dnicolson** [comment]
It looks like only `@middy/core` was published with version v4.0.5.

**Comment by dnicolson** [comment]
I get the following error with v4.0.5:
```
Cannot find module 'ajv-cmd/compile' from 'node_modules/@middy/validator/transpile.cjs'
```

**Comment by willfarrell** [comment]
I’ll take a look this afternoon. See if I can write a test. Thank for your patience with this.

**Comment by willfarrell** [comment]
Added in a test for this specifically, 4.0.7 should do it, I hope.

**Comment by gregschroeder** [comment]
yes!  v4.0.7 works.  big thanks!
