### ISSUE TITLE
You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by Tamir198** [middyjs/middy#976]
I am using Serverless Framework and it seems like middy is not compatible with it.

Bug description
-

In my serverless Framework project I have a function named `createAuction` and when I try to wrap middy around it like this (check the last line):

```js

async function createAuction(event, context) {
  const dynamoDb = new AWS.DynamoDB.DocumentClient();
  const { title } = JSON.parse(event.body);

  const auction = {
    title: title,
    id: uuid.call(),
    status: "open",
    creationTime: new Date().toISOString(),
  };

  //The aws sdk is using callbacks, the promise in here so we can use await
  await dynamoDb
    .put({ TableName: process.env.AUCTIONS_TABLE_NAME, Item: auction })
    .promise();

  return {
    statusCode: 201,
    body: JSON.stringify(auction),
  };
}

export const handler = middy(createAuction);

```

I am getting this error when I try to deploy createAuction with middy :

```js
Module parse failed: Unexpected token (19:26)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

<details>
  <summary>The full error</summary>
  
  ```js
   Error:
Error: Webpack compilation error, see above
    at G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\serverless-webpack\lib\compile.js:38:19
    at arrayEach (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\lodash\lodash.js:516:11)
    at Function.forEach (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\lodash\lodash.js:9342:14)
    at G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\serverless-webpack\lib\compile.js:31:11
    at tryCatcher (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\bluebird\js\release\promise.js:604:18)    
    at Promise._settlePromise0 (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\bluebird\js\release\promise.js:649:10)   
    at Promise._settlePromises (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\bluebird\js\release\promise.js:729:18)   
    at Promise._fulfill (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\bluebird\js\release\promise.js:673:18)
    at G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\bluebird\js\release\nodeback.js:42:21
    at finalCallback (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\webpack\lib\Compiler.js:257:39)
    at G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\webpack\lib\Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\tapable\lib\Hook.js:154:20)      
    at onCompiled (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\webpack\lib\Compiler.js:271:21)
    at G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\webpack\lib\Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\tapable\lib\Hook.js:154:20)      
    at G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\webpack\lib\Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\tapable\lib\Hook.js:154:20)      
    at G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\webpack\lib\Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\tapable\lib\Hook.js:154:20)      
    at G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\webpack\lib\Compilation.js:1414:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\tapable\lib\Hook.js:154:20)      
    at G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\webpack\lib\Compilation.js:1409:36
    at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\tapable\lib\Hook.js:154:20)      
    at G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\webpack\lib\Compilation.js:1405:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\tapable\lib\Hook.js:154:20)      
    at Compilation.seal (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\webpack\lib\Compilation.js:1342:27)
    at G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\webpack\lib\Compiler.js:675:18
    at G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\webpack\lib\Compilation.js:1261:4
    at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\tapable\lib\Hook.js:154:20)      
    at Compilation.finish (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\webpack\lib\Compilation.js:1253:28)
    at G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\webpack\lib\Compiler.js:672:17
    at eval (eval at create (G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
    at G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\webpack\lib\Compilation.js:1185:12
    at G:\TAMIR\Desktop\Serverless-Framework\auction-service\node_modules\webpack\lib\Compilation.js:1097:9
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
  ```
</details>

Deploy command ` serverless deploy -f createAuction`

Environment 
```js
"@middy/core": "^4.0.9",
"aws-sdk": "^2.639.0",
node 14.17.3
```

**Comment by Tamir198** [comment]
I think that the problem was that I used old version of the Serverless Framework template
I will check this, and that will be the problem I will close this issue

**Comment by willfarrell** [comment]
If you're using NodeJS 14, you may want to use Middy v3 instead. Middy v4 is for NodeJS 16/18. This might be the source of the issue.
